version: 2.0
jobs:
  gcc:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # GCC
      - run:
          name: GCC build + MPI
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            source /etc/profile.d/modules.sh
            export MODULEPATH=$MODULEPATH:/usr/share/modulefiles
            module load mpi/openmpi-x86_64
            export CXX_COMPILER=mpicxx
            cmake -GNinja -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            ninja -j2
            ctest -VV
            mpirun -n 4 ./mpmtest [mpi]
  clang:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # Clang
      - run:
          name: Clang + Static analysis
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            scan-build cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            scan-build -k -V ninja -j2
            ctest -VV
  cppcheck:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      - run:
          name: cppcheck/clang-format
          command: |
            cppcheck --version
            cppcheck --inline-suppr --enable=warning --inconclusive --force --language=c++ --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1
      # clang-format
      - run:
          name: clang-format
          command: |
            python3 ./clang-tools/run-clang-format.py -r include/* src/* tests/*

  codecov:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout

      # codecoverage
      - run:
          name: codecov.io
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DENABLE_COVERAGE=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            make mpmtest_coverage -j2
            ./mpmtest_coverage
            mpirun -n 4 ./mpmtest_coverage [mpi]
            lcov --directory . --capture --output-file coverage.info
            bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

  benchmarks:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # GCC
      - run:
          name: GCC build + MPI
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            source /etc/profile.d/modules.sh
            export MODULEPATH=$MODULEPATH:/usr/share/modulefiles
            module load mpi/openmpi-x86_64
            export CXX_COMPILER=mpicxx
            cmake -GNinja -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            ninja -j2
            ctest -VV
            mpirun -n 4 ./mpmtest [mpi]
      # Benchmarks
      - run:
          name: Clone benchmarks
          command: |
            cd /home/cbgeo/project/build
            git clone https://github.com/cb-geo/mpm-benchmarks.git benchmarks
      # Benchmarks
      - run:
          name: 2D sliding block
          command: |
            cd /home/cbgeo/project/build
            pip3 install tables --user
            export OMP_NUM_THREADS=2
            mpirun -n 4 ./mpm -f ./benchmarks/2d/sliding_block_inclined_boundary/
            python3 ./benchmarks/2d/sliding_block_inclined_boundary/test_benchmark.py
      # Stress
      - run:
          name: Uniaxial stress
          command: |
            cd /home/cbgeo/project/build
            ./mpm -f ./benchmarks/2d/uniaxial_stress/
            python3 ./benchmarks/2d/uniaxial_stress/test_benchmark.py
      # Traction
      - run:
          name: Uniaxial traction
          command: |
            cd /home/cbgeo/project/build
            export OMP_NUM_THREADS=2
            ./mpm -f ./benchmarks/2d/uniaxial_traction/ -i mpm-nodal-forces.json
            ./mpm -f ./benchmarks/2d/uniaxial_traction/ -i mpm-particle-traction.json
            python3 ./benchmarks/2d/uniaxial_stress/test_benchmark.py

workflows:
    version: 2
    build:
        jobs:
            - gcc
            - clang
            - cppcheck
            - codecov
            - benchmarks
    nightly:
        jobs:
            - benchmarks
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only:
                          - develop