version: 2.0
jobs:
  build:
    working_directory: /home/cbgeo/research/mpm
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # GCC-8
      - run:
          name: GCC-8 build + MPI
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            source /etc/profile.d/modules.sh
            export MODULEPATH=$MODULEPATH:/usr/share/modulefiles
            module load mpi/openmpi-x86_64
            export CXX_COMPILER=mpicxx
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
            make -j2
            ctest -VV
      # Clang-6.0
      - run:
          name: Clang-6.0 + Static analysis
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            scan-build cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
            scan-build make -j2 
            ctest -VV
      # cppcheck
      - run:
          name: cppcheck
          command: |
            cppcheck --version
            cppcheck --inline-suppr --enable=warning --inconclusive --force --language=c++ --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1
      # clang-format
      - run:
          name: clang-format
          command: |
            python3 ./clang-tools/run-clang-format.py -r include/* src/* tests/*
      # codecoverage
      - run:
          name: codecov.io
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DENABLE_COVERAGE=On ..
            make mpmtest_coverage -j2
            ./mpmtest_coverage
            make gcov -j2  --ignore-errors
            make lcov
            bash <(curl -s https://codecov.io/bash) -X gcov
