version: 2.0
jobs:
  gcc:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # GCC-8
      - run:
          name: GCC-8 build + MPI
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            source /etc/profile.d/modules.sh
            export MODULEPATH=$MODULEPATH:/usr/share/modulefiles
            module load mpi/openmpi-x86_64
            export CXX_COMPILER=mpicxx
            export PETSC_ARCH=arch-linux2-c-opt
            export PETSC_DIR=/home/cbgeo/petsc/
            cmake -GNinja -DMPM_BUILD_LIB=On -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            ninja -j2
            ctest -VV
            mpirun -n 4 ./mpmtest [mpi]
  clang:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      # Clang-6.0
      - run:
          name: Clang-6.0 + Static analysis
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            export PETSC_ARCH=arch-linux2-c-opt
            export PETSC_DIR=/home/cbgeo/petsc/
            scan-build cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DMPM_BUILD_LIB=On -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            scan-build -k -V ninja -j2
            ctest -VV
  cppcheck:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout
      - run:
          name: cppcheck
          command: |
            cppcheck --version
            cppcheck --inline-suppr --enable=warning --inconclusive --force --language=c++ --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1
      # clang-format
      - run:
          name: clang-format
          command: |
            python3 ./clang-tools/run-clang-format.py -r include/* src/* tests/*

  codecov:
    docker:
      - image: quay.io/cbgeo/mpm
    steps:
      - checkout

      # codecoverage
      - run:
          name: codecov.io
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            export PETSC_ARCH=arch-linux2-c-opt
            export PETSC_DIR=/home/cbgeo/petsc/
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DENABLE_COVERAGE=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
            make mpmtest_coverage -j2
            ./mpmtest_coverage
            mpirun -n 4 ./mpmtest_coverage [mpi]
            lcov --directory . --capture --output-file coverage.info
            bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

workflows:
    version: 2
    build:
        jobs:
            - gcc
            - clang
            - cppcheck
            - codecov
